### ISSUE TITLE
Bug in sqlite3::connection::escape() ?

### ISSUE THREAD

**Issue by niXman** [rbock/sqlpp11-connector-sqlite3#7]
Hi,

What is the sense in this condition? It is senseless =)
https://github.com/rbock/sqlpp11-connector-sqlite3/blob/master/src/connection.cpp#L177

In addition, I do not understand why the other characters such as the following are not escaped: '\n', '\t', '\v', '\b', '\r', '\f', '\a', '\\', '\'', '\"'

I have some experience of using databases and I could be wrong...

**Comment by rbock** [comment]
Hi,

Taken from here: http://www.sqlite.org/lang_expr.html

"A string constant is formed by enclosing the string in single quotes ('). A single quote within the string can be encoded by putting two single quotes in a row - as in Pascal. C-style escapes using the backslash character are not supported because they are not standard SQL."

Regards,

Roland

**Comment by niXman** [comment]
Hmm...this is strange...
Ok, closed.

Thanks.

**Comment by rbock** [comment]
Now you made me curious. What is strange? You got a problem with some query?

**Comment by niXman** [comment]
No, I just reviewing the code and such way of escaping seemed to me unusual. Later I'll check real query/escaping.

I'm sorry to interrupt you.

**Comment by rbock** [comment]
Don't worry :-)
